// Generated by gencpp from file hdt_adroit_driver/Commit.msg
// DO NOT EDIT!


#ifndef HDT_ADROIT_DRIVER_MESSAGE_COMMIT_H
#define HDT_ADROIT_DRIVER_MESSAGE_COMMIT_H

#include <ros/service_traits.h>


#include <hdt_adroit_driver/CommitRequest.h>
#include <hdt_adroit_driver/CommitResponse.h>


namespace hdt_adroit_driver
{

struct Commit
{

typedef CommitRequest Request;
typedef CommitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Commit
} // namespace hdt_adroit_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hdt_adroit_driver::Commit > {
  static const char* value()
  {
    return "13ff23040aab9b4302a107a8c3ff196a";
  }

  static const char* value(const ::hdt_adroit_driver::Commit&) { return value(); }
};

template<>
struct DataType< ::hdt_adroit_driver::Commit > {
  static const char* value()
  {
    return "hdt_adroit_driver/Commit";
  }

  static const char* value(const ::hdt_adroit_driver::Commit&) { return value(); }
};


// service_traits::MD5Sum< ::hdt_adroit_driver::CommitRequest> should match 
// service_traits::MD5Sum< ::hdt_adroit_driver::Commit > 
template<>
struct MD5Sum< ::hdt_adroit_driver::CommitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hdt_adroit_driver::Commit >::value();
  }
  static const char* value(const ::hdt_adroit_driver::CommitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdt_adroit_driver::CommitRequest> should match 
// service_traits::DataType< ::hdt_adroit_driver::Commit > 
template<>
struct DataType< ::hdt_adroit_driver::CommitRequest>
{
  static const char* value()
  {
    return DataType< ::hdt_adroit_driver::Commit >::value();
  }
  static const char* value(const ::hdt_adroit_driver::CommitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hdt_adroit_driver::CommitResponse> should match 
// service_traits::MD5Sum< ::hdt_adroit_driver::Commit > 
template<>
struct MD5Sum< ::hdt_adroit_driver::CommitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hdt_adroit_driver::Commit >::value();
  }
  static const char* value(const ::hdt_adroit_driver::CommitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdt_adroit_driver::CommitResponse> should match 
// service_traits::DataType< ::hdt_adroit_driver::Commit > 
template<>
struct DataType< ::hdt_adroit_driver::CommitResponse>
{
  static const char* value()
  {
    return DataType< ::hdt_adroit_driver::Commit >::value();
  }
  static const char* value(const ::hdt_adroit_driver::CommitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HDT_ADROIT_DRIVER_MESSAGE_COMMIT_H
