// Generated by gencpp from file hdt_adroit_driver/ComsReady.msg
// DO NOT EDIT!


#ifndef HDT_ADROIT_DRIVER_MESSAGE_COMSREADY_H
#define HDT_ADROIT_DRIVER_MESSAGE_COMSREADY_H

#include <ros/service_traits.h>


#include <hdt_adroit_driver/ComsReadyRequest.h>
#include <hdt_adroit_driver/ComsReadyResponse.h>


namespace hdt_adroit_driver
{

struct ComsReady
{

typedef ComsReadyRequest Request;
typedef ComsReadyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComsReady
} // namespace hdt_adroit_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hdt_adroit_driver::ComsReady > {
  static const char* value()
  {
    return "cccee9ec3b01334c5ae62ca025ff5526";
  }

  static const char* value(const ::hdt_adroit_driver::ComsReady&) { return value(); }
};

template<>
struct DataType< ::hdt_adroit_driver::ComsReady > {
  static const char* value()
  {
    return "hdt_adroit_driver/ComsReady";
  }

  static const char* value(const ::hdt_adroit_driver::ComsReady&) { return value(); }
};


// service_traits::MD5Sum< ::hdt_adroit_driver::ComsReadyRequest> should match 
// service_traits::MD5Sum< ::hdt_adroit_driver::ComsReady > 
template<>
struct MD5Sum< ::hdt_adroit_driver::ComsReadyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hdt_adroit_driver::ComsReady >::value();
  }
  static const char* value(const ::hdt_adroit_driver::ComsReadyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdt_adroit_driver::ComsReadyRequest> should match 
// service_traits::DataType< ::hdt_adroit_driver::ComsReady > 
template<>
struct DataType< ::hdt_adroit_driver::ComsReadyRequest>
{
  static const char* value()
  {
    return DataType< ::hdt_adroit_driver::ComsReady >::value();
  }
  static const char* value(const ::hdt_adroit_driver::ComsReadyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hdt_adroit_driver::ComsReadyResponse> should match 
// service_traits::MD5Sum< ::hdt_adroit_driver::ComsReady > 
template<>
struct MD5Sum< ::hdt_adroit_driver::ComsReadyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hdt_adroit_driver::ComsReady >::value();
  }
  static const char* value(const ::hdt_adroit_driver::ComsReadyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdt_adroit_driver::ComsReadyResponse> should match 
// service_traits::DataType< ::hdt_adroit_driver::ComsReady > 
template<>
struct DataType< ::hdt_adroit_driver::ComsReadyResponse>
{
  static const char* value()
  {
    return DataType< ::hdt_adroit_driver::ComsReady >::value();
  }
  static const char* value(const ::hdt_adroit_driver::ComsReadyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HDT_ADROIT_DRIVER_MESSAGE_COMSREADY_H
