// Generated by gencpp from file hdt_adroit_driver/GetStatus.msg
// DO NOT EDIT!


#ifndef HDT_ADROIT_DRIVER_MESSAGE_GETSTATUS_H
#define HDT_ADROIT_DRIVER_MESSAGE_GETSTATUS_H

#include <ros/service_traits.h>


#include <hdt_adroit_driver/GetStatusRequest.h>
#include <hdt_adroit_driver/GetStatusResponse.h>


namespace hdt_adroit_driver
{

struct GetStatus
{

typedef GetStatusRequest Request;
typedef GetStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStatus
} // namespace hdt_adroit_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hdt_adroit_driver::GetStatus > {
  static const char* value()
  {
    return "030d6b61cd649925cba2336b4a1efa95";
  }

  static const char* value(const ::hdt_adroit_driver::GetStatus&) { return value(); }
};

template<>
struct DataType< ::hdt_adroit_driver::GetStatus > {
  static const char* value()
  {
    return "hdt_adroit_driver/GetStatus";
  }

  static const char* value(const ::hdt_adroit_driver::GetStatus&) { return value(); }
};


// service_traits::MD5Sum< ::hdt_adroit_driver::GetStatusRequest> should match 
// service_traits::MD5Sum< ::hdt_adroit_driver::GetStatus > 
template<>
struct MD5Sum< ::hdt_adroit_driver::GetStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hdt_adroit_driver::GetStatus >::value();
  }
  static const char* value(const ::hdt_adroit_driver::GetStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdt_adroit_driver::GetStatusRequest> should match 
// service_traits::DataType< ::hdt_adroit_driver::GetStatus > 
template<>
struct DataType< ::hdt_adroit_driver::GetStatusRequest>
{
  static const char* value()
  {
    return DataType< ::hdt_adroit_driver::GetStatus >::value();
  }
  static const char* value(const ::hdt_adroit_driver::GetStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hdt_adroit_driver::GetStatusResponse> should match 
// service_traits::MD5Sum< ::hdt_adroit_driver::GetStatus > 
template<>
struct MD5Sum< ::hdt_adroit_driver::GetStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hdt_adroit_driver::GetStatus >::value();
  }
  static const char* value(const ::hdt_adroit_driver::GetStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdt_adroit_driver::GetStatusResponse> should match 
// service_traits::DataType< ::hdt_adroit_driver::GetStatus > 
template<>
struct DataType< ::hdt_adroit_driver::GetStatusResponse>
{
  static const char* value()
  {
    return DataType< ::hdt_adroit_driver::GetStatus >::value();
  }
  static const char* value(const ::hdt_adroit_driver::GetStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HDT_ADROIT_DRIVER_MESSAGE_GETSTATUS_H
