// Generated by gencpp from file hdt_adroit_driver/GetStatusResponse.msg
// DO NOT EDIT!


#ifndef HDT_ADROIT_DRIVER_MESSAGE_GETSTATUSRESPONSE_H
#define HDT_ADROIT_DRIVER_MESSAGE_GETSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hdt_adroit_driver
{
template <class ContainerAllocator>
struct GetStatusResponse_
{
  typedef GetStatusResponse_<ContainerAllocator> Type;

  GetStatusResponse_()
    : addr()
    , state()  {
    }
  GetStatusResponse_(const ContainerAllocator& _alloc)
    : addr(_alloc)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _addr_type;
  _addr_type addr;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetStatusResponse_

typedef ::hdt_adroit_driver::GetStatusResponse_<std::allocator<void> > GetStatusResponse;

typedef boost::shared_ptr< ::hdt_adroit_driver::GetStatusResponse > GetStatusResponsePtr;
typedef boost::shared_ptr< ::hdt_adroit_driver::GetStatusResponse const> GetStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hdt_adroit_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'hdt_adroit_driver': ['/home/arl/Hdt_arms_VT/catkin_ws/src/hdt_adroit_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "030d6b61cd649925cba2336b4a1efa95";
  }

  static const char* value(const ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x030d6b61cd649925ULL;
  static const uint64_t static_value2 = 0xcba2336b4a1efa95ULL;
};

template<class ContainerAllocator>
struct DataType< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hdt_adroit_driver/GetStatusResponse";
  }

  static const char* value(const ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] addr\n\
uint32[] state\n\
\n\
";
  }

  static const char* value(const ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.addr);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hdt_adroit_driver::GetStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "addr[]" << std::endl;
    for (size_t i = 0; i < v.addr.size(); ++i)
    {
      s << indent << "  addr[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.addr[i]);
    }
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDT_ADROIT_DRIVER_MESSAGE_GETSTATUSRESPONSE_H
