// Generated by gencpp from file hdt_adroit_driver/HDTLSTelem.msg
// DO NOT EDIT!


#ifndef HDT_ADROIT_DRIVER_MESSAGE_HDTLSTELEM_H
#define HDT_ADROIT_DRIVER_MESSAGE_HDTLSTELEM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hdt_adroit_driver
{
template <class ContainerAllocator>
struct HDTLSTelem_
{
  typedef HDTLSTelem_<ContainerAllocator> Type;

  HDTLSTelem_()
    : bus_voltage(0.0)
    , bus_current(0.0)
    , temperature(0.0)  {
    }
  HDTLSTelem_(const ContainerAllocator& _alloc)
    : bus_voltage(0.0)
    , bus_current(0.0)
    , temperature(0.0)  {
  (void)_alloc;
    }



   typedef float _bus_voltage_type;
  _bus_voltage_type bus_voltage;

   typedef float _bus_current_type;
  _bus_current_type bus_current;

   typedef float _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> const> ConstPtr;

}; // struct HDTLSTelem_

typedef ::hdt_adroit_driver::HDTLSTelem_<std::allocator<void> > HDTLSTelem;

typedef boost::shared_ptr< ::hdt_adroit_driver::HDTLSTelem > HDTLSTelemPtr;
typedef boost::shared_ptr< ::hdt_adroit_driver::HDTLSTelem const> HDTLSTelemConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hdt_adroit_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'hdt_adroit_driver': ['/home/arl/catkin_ws/src/hdt_adroit_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6482f2ccdad1eb7d5847af2e454494b";
  }

  static const char* value(const ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6482f2ccdad1eb7ULL;
  static const uint64_t static_value2 = 0xd5847af2e454494bULL;
};

template<class ContainerAllocator>
struct DataType< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hdt_adroit_driver/HDTLSTelem";
  }

  static const char* value(const ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 bus_voltage\n\
float32 bus_current\n\
float32 temperature\n\
";
  }

  static const char* value(const ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bus_voltage);
      stream.next(m.bus_current);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HDTLSTelem_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hdt_adroit_driver::HDTLSTelem_<ContainerAllocator>& v)
  {
    s << indent << "bus_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.bus_voltage);
    s << indent << "bus_current: ";
    Printer<float>::stream(s, indent + "  ", v.bus_current);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDT_ADROIT_DRIVER_MESSAGE_HDTLSTELEM_H
