// Generated by gencpp from file hdt_adroit_driver/HDTMSTelem.msg
// DO NOT EDIT!


#ifndef HDT_ADROIT_DRIVER_MESSAGE_HDTMSTELEM_H
#define HDT_ADROIT_DRIVER_MESSAGE_HDTMSTELEM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hdt_adroit_driver
{
template <class ContainerAllocator>
struct HDTMSTelem_
{
  typedef HDTMSTelem_<ContainerAllocator> Type;

  HDTMSTelem_()
    : var1(0)
    , var2(0)
    , var3(0)
    , var4(0)  {
    }
  HDTMSTelem_(const ContainerAllocator& _alloc)
    : var1(0)
    , var2(0)
    , var3(0)
    , var4(0)  {
  (void)_alloc;
    }



   typedef int16_t _var1_type;
  _var1_type var1;

   typedef int16_t _var2_type;
  _var2_type var2;

   typedef int16_t _var3_type;
  _var3_type var3;

   typedef int16_t _var4_type;
  _var4_type var4;





  typedef boost::shared_ptr< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> const> ConstPtr;

}; // struct HDTMSTelem_

typedef ::hdt_adroit_driver::HDTMSTelem_<std::allocator<void> > HDTMSTelem;

typedef boost::shared_ptr< ::hdt_adroit_driver::HDTMSTelem > HDTMSTelemPtr;
typedef boost::shared_ptr< ::hdt_adroit_driver::HDTMSTelem const> HDTMSTelemConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hdt_adroit_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'hdt_adroit_driver': ['/home/arl/Hdt_arms_VT/catkin_ws/src/hdt_adroit_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6dc00f8899a8207abb48266da6b58569";
  }

  static const char* value(const ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6dc00f8899a8207aULL;
  static const uint64_t static_value2 = 0xbb48266da6b58569ULL;
};

template<class ContainerAllocator>
struct DataType< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hdt_adroit_driver/HDTMSTelem";
  }

  static const char* value(const ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 var1\n\
int16 var2\n\
int16 var3\n\
int16 var4\n\
";
  }

  static const char* value(const ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.var1);
      stream.next(m.var2);
      stream.next(m.var3);
      stream.next(m.var4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HDTMSTelem_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hdt_adroit_driver::HDTMSTelem_<ContainerAllocator>& v)
  {
    s << indent << "var1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.var1);
    s << indent << "var2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.var2);
    s << indent << "var3: ";
    Printer<int16_t>::stream(s, indent + "  ", v.var3);
    s << indent << "var4: ";
    Printer<int16_t>::stream(s, indent + "  ", v.var4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDT_ADROIT_DRIVER_MESSAGE_HDTMSTELEM_H
