// Generated by gencpp from file hdt_adroit_driver/ReadDriveParam.msg
// DO NOT EDIT!


#ifndef HDT_ADROIT_DRIVER_MESSAGE_READDRIVEPARAM_H
#define HDT_ADROIT_DRIVER_MESSAGE_READDRIVEPARAM_H

#include <ros/service_traits.h>


#include <hdt_adroit_driver/ReadDriveParamRequest.h>
#include <hdt_adroit_driver/ReadDriveParamResponse.h>


namespace hdt_adroit_driver
{

struct ReadDriveParam
{

typedef ReadDriveParamRequest Request;
typedef ReadDriveParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadDriveParam
} // namespace hdt_adroit_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hdt_adroit_driver::ReadDriveParam > {
  static const char* value()
  {
    return "bb5aec711104386e2aeb8b52f04e2a7a";
  }

  static const char* value(const ::hdt_adroit_driver::ReadDriveParam&) { return value(); }
};

template<>
struct DataType< ::hdt_adroit_driver::ReadDriveParam > {
  static const char* value()
  {
    return "hdt_adroit_driver/ReadDriveParam";
  }

  static const char* value(const ::hdt_adroit_driver::ReadDriveParam&) { return value(); }
};


// service_traits::MD5Sum< ::hdt_adroit_driver::ReadDriveParamRequest> should match 
// service_traits::MD5Sum< ::hdt_adroit_driver::ReadDriveParam > 
template<>
struct MD5Sum< ::hdt_adroit_driver::ReadDriveParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hdt_adroit_driver::ReadDriveParam >::value();
  }
  static const char* value(const ::hdt_adroit_driver::ReadDriveParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdt_adroit_driver::ReadDriveParamRequest> should match 
// service_traits::DataType< ::hdt_adroit_driver::ReadDriveParam > 
template<>
struct DataType< ::hdt_adroit_driver::ReadDriveParamRequest>
{
  static const char* value()
  {
    return DataType< ::hdt_adroit_driver::ReadDriveParam >::value();
  }
  static const char* value(const ::hdt_adroit_driver::ReadDriveParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hdt_adroit_driver::ReadDriveParamResponse> should match 
// service_traits::MD5Sum< ::hdt_adroit_driver::ReadDriveParam > 
template<>
struct MD5Sum< ::hdt_adroit_driver::ReadDriveParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hdt_adroit_driver::ReadDriveParam >::value();
  }
  static const char* value(const ::hdt_adroit_driver::ReadDriveParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdt_adroit_driver::ReadDriveParamResponse> should match 
// service_traits::DataType< ::hdt_adroit_driver::ReadDriveParam > 
template<>
struct DataType< ::hdt_adroit_driver::ReadDriveParamResponse>
{
  static const char* value()
  {
    return DataType< ::hdt_adroit_driver::ReadDriveParam >::value();
  }
  static const char* value(const ::hdt_adroit_driver::ReadDriveParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HDT_ADROIT_DRIVER_MESSAGE_READDRIVEPARAM_H
