// Generated by gencpp from file hdt_adroit_driver/WriteDriveParam.msg
// DO NOT EDIT!


#ifndef HDT_ADROIT_DRIVER_MESSAGE_WRITEDRIVEPARAM_H
#define HDT_ADROIT_DRIVER_MESSAGE_WRITEDRIVEPARAM_H

#include <ros/service_traits.h>


#include <hdt_adroit_driver/WriteDriveParamRequest.h>
#include <hdt_adroit_driver/WriteDriveParamResponse.h>


namespace hdt_adroit_driver
{

struct WriteDriveParam
{

typedef WriteDriveParamRequest Request;
typedef WriteDriveParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WriteDriveParam
} // namespace hdt_adroit_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hdt_adroit_driver::WriteDriveParam > {
  static const char* value()
  {
    return "9bd87f56854479b390ba5369522b5546";
  }

  static const char* value(const ::hdt_adroit_driver::WriteDriveParam&) { return value(); }
};

template<>
struct DataType< ::hdt_adroit_driver::WriteDriveParam > {
  static const char* value()
  {
    return "hdt_adroit_driver/WriteDriveParam";
  }

  static const char* value(const ::hdt_adroit_driver::WriteDriveParam&) { return value(); }
};


// service_traits::MD5Sum< ::hdt_adroit_driver::WriteDriveParamRequest> should match 
// service_traits::MD5Sum< ::hdt_adroit_driver::WriteDriveParam > 
template<>
struct MD5Sum< ::hdt_adroit_driver::WriteDriveParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hdt_adroit_driver::WriteDriveParam >::value();
  }
  static const char* value(const ::hdt_adroit_driver::WriteDriveParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdt_adroit_driver::WriteDriveParamRequest> should match 
// service_traits::DataType< ::hdt_adroit_driver::WriteDriveParam > 
template<>
struct DataType< ::hdt_adroit_driver::WriteDriveParamRequest>
{
  static const char* value()
  {
    return DataType< ::hdt_adroit_driver::WriteDriveParam >::value();
  }
  static const char* value(const ::hdt_adroit_driver::WriteDriveParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hdt_adroit_driver::WriteDriveParamResponse> should match 
// service_traits::MD5Sum< ::hdt_adroit_driver::WriteDriveParam > 
template<>
struct MD5Sum< ::hdt_adroit_driver::WriteDriveParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hdt_adroit_driver::WriteDriveParam >::value();
  }
  static const char* value(const ::hdt_adroit_driver::WriteDriveParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdt_adroit_driver::WriteDriveParamResponse> should match 
// service_traits::DataType< ::hdt_adroit_driver::WriteDriveParam > 
template<>
struct DataType< ::hdt_adroit_driver::WriteDriveParamResponse>
{
  static const char* value()
  {
    return DataType< ::hdt_adroit_driver::WriteDriveParam >::value();
  }
  static const char* value(const ::hdt_adroit_driver::WriteDriveParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HDT_ADROIT_DRIVER_MESSAGE_WRITEDRIVEPARAM_H
