; Auto-generated. Do not edit!


(cl:in-package hdt_arm_control-msg)


;//! \htmlinclude TaskSpacePathGoal.msg.html

(cl:defclass <TaskSpacePathGoal> (roslisp-msg-protocol:ros-message)
  ((marker
    :reader marker
    :initarg :marker
    :type cl:string
    :initform "")
   (pose
    :reader pose
    :initarg :pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass TaskSpacePathGoal (<TaskSpacePathGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TaskSpacePathGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TaskSpacePathGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hdt_arm_control-msg:<TaskSpacePathGoal> is deprecated: use hdt_arm_control-msg:TaskSpacePathGoal instead.")))

(cl:ensure-generic-function 'marker-val :lambda-list '(m))
(cl:defmethod marker-val ((m <TaskSpacePathGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hdt_arm_control-msg:marker-val is deprecated.  Use hdt_arm_control-msg:marker instead.")
  (marker m))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <TaskSpacePathGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hdt_arm_control-msg:pose-val is deprecated.  Use hdt_arm_control-msg:pose instead.")
  (pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TaskSpacePathGoal>) ostream)
  "Serializes a message object of type '<TaskSpacePathGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'marker))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'marker))
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TaskSpacePathGoal>) istream)
  "Deserializes a message object of type '<TaskSpacePathGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'marker) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'marker) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TaskSpacePathGoal>)))
  "Returns string type for a message object of type '<TaskSpacePathGoal>"
  "hdt_arm_control/TaskSpacePathGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TaskSpacePathGoal)))
  "Returns string type for a message object of type 'TaskSpacePathGoal"
  "hdt_arm_control/TaskSpacePathGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TaskSpacePathGoal>)))
  "Returns md5sum for a message object of type '<TaskSpacePathGoal>"
  "626e41bcfa7cee736185c3d82f41f083")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TaskSpacePathGoal)))
  "Returns md5sum for a message object of type 'TaskSpacePathGoal"
  "626e41bcfa7cee736185c3d82f41f083")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TaskSpacePathGoal>)))
  "Returns full string definition for message of type '<TaskSpacePathGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%string marker~%geometry_msgs/Pose pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TaskSpacePathGoal)))
  "Returns full string definition for message of type 'TaskSpacePathGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%string marker~%geometry_msgs/Pose pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TaskSpacePathGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'marker))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TaskSpacePathGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TaskSpacePathGoal
    (cl:cons ':marker (marker msg))
    (cl:cons ':pose (pose msg))
))
