controller_list:
  - name: fake_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
  - name: fake_hand_controller
    joints:
      - index_prox
      - ring_prox
      - thumb_base
      - thumb_prox