arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6, joint_7]
hand_controller:
    type: "position_controllers/JointTrajectoryController"
    joints: [index_prox, thumb_prox, ring_prox, thumb_base]
joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

