hdt_saffir:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500

  # Position Controllers ---------------------------------------
  # Right
  right/joint1_position_controller:
    type: effort_controllers/JointEffortController
    joint: right/joint1
    pid: {p: 100.0, i: 0.1, d: 10.0}
  right/joint2_position_controller:
    type: effort_controllers/JointEffortController
    joint: right/joint2
    pid: {p: 100.0, i: 0.1, d: 10.0}
  right/joint4_position_controller:
    type: effort_controllers/JointEffortController
    joint: right/joint4
    pid: {p: 100.0, i: 0.1, d: 10.0}
  right/joint5_position_controller:
    type: effort_controllers/JointEffortController
    joint: right/joint5
    pid: {p: 100.0, i: 0.1, d: 10.0}
  right/joint6_position_controller:
    type: effort_controllers/JointEffortController
    joint: right/joint6
    pid: {p: 100.0, i: 0.1, d: 10.0}
  right/joint7_position_controller:
    type: effort_controllers/JointEffortController
    joint: right/joint7
    pid: {p: 100.0, i: 0.1, d: 10.0}
  right/thumb_base_position_controller:
    type: effort_controllers/JointEffortController
    joint: right/thumb_base
    pid: {p: 100.0, i: 0.1, d: 10.0}
  right/thumb_prox_position_controller:
    type: effort_controllers/JointEffortController
    joint: right/thumb_prox
    pid: {p: 100.0, i: 0.1, d: 10.0}
  right/index_prox_position_controller:
    type: effort_controllers/JointEffortController
    joint: right/index_prox
    pid: {p: 100.0, i: 0.1, d: 10.0}
  right/ring_prox_position_controller:
    type: effort_controllers/JointEffortController
    joint: right/ring_prox
    pid: {p: 100.0, i: 0.1, d: 10.0}
  # Left
  left/joint1_position_controller:
    type: effort_controllers/JointEffortController
    joint: left/joint1
    pid: {p: 100.0, i: 0.1, d: 10.0}
  left/joint2_position_controller:
    type: effort_controllers/JointEffortController
    joint: left/joint2
    pid: {p: 100.0, i: 0.1, d: 10.0}
  left/joint4_position_controller:
    type: effort_controllers/JointEffortController
    joint: left/joint4
    pid: {p: 100.0, i: 0.1, d: 10.0}
  left/joint5_position_controller:
    type: effort_controllers/JointEffortController
    joint: left/joint5
    pid: {p: 100.0, i: 0.1, d: 10.0}
  left/joint6_position_controller:
    type: effort_controllers/JointEffortController
    joint: left/joint6
    pid: {p: 100.0, i: 0.1, d: 10.0}
  left/joint7_position_controller:
    type: effort_controllers/JointEffortController
    joint: left/joint7
    pid: {p: 100.0, i: 0.1, d: 10.0}
  left/thumb_base_position_controller:
    type: effort_controllers/JointEffortController
    joint: left/thumb_base
    pid: {p: 100.0, i: 0.1, d: 10.0}
  left/thumb_prox_position_controller:
    type: effort_controllers/JointEffortController
    joint: left/thumb_prox
    pid: {p: 100.0, i: 0.1, d: 10.0}
  left/index_prox_position_controller:
    type: effort_controllers/JointEffortController
    joint: left/index_prox
    pid: {p: 100.0, i: 0.1, d: 10.0}
  left/ring_prox_position_controller:
    type: effort_controllers/JointEffortController
    joint: left/ring_prox
    pid: {p: 100.0, i: 0.1, d: 10.0}
