; Auto-generated. Do not edit!


(cl:in-package hdt_saffir_control-msg)


;//! \htmlinclude JointSpacePathGoal.msg.html

(cl:defclass <JointSpacePathGoal> (roslisp-msg-protocol:ros-message)
  ((pose
    :reader pose
    :initarg :pose
    :type cl:string
    :initform ""))
)

(cl:defclass JointSpacePathGoal (<JointSpacePathGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JointSpacePathGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JointSpacePathGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hdt_saffir_control-msg:<JointSpacePathGoal> is deprecated: use hdt_saffir_control-msg:JointSpacePathGoal instead.")))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <JointSpacePathGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hdt_saffir_control-msg:pose-val is deprecated.  Use hdt_saffir_control-msg:pose instead.")
  (pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JointSpacePathGoal>) ostream)
  "Serializes a message object of type '<JointSpacePathGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'pose))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'pose))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JointSpacePathGoal>) istream)
  "Deserializes a message object of type '<JointSpacePathGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'pose) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'pose) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JointSpacePathGoal>)))
  "Returns string type for a message object of type '<JointSpacePathGoal>"
  "hdt_saffir_control/JointSpacePathGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JointSpacePathGoal)))
  "Returns string type for a message object of type 'JointSpacePathGoal"
  "hdt_saffir_control/JointSpacePathGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JointSpacePathGoal>)))
  "Returns md5sum for a message object of type '<JointSpacePathGoal>"
  "0cbc29f91adcb71214b885e1c0073aa7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JointSpacePathGoal)))
  "Returns md5sum for a message object of type 'JointSpacePathGoal"
  "0cbc29f91adcb71214b885e1c0073aa7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JointSpacePathGoal>)))
  "Returns full string definition for message of type '<JointSpacePathGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%string pose~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JointSpacePathGoal)))
  "Returns full string definition for message of type 'JointSpacePathGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%string pose~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JointSpacePathGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JointSpacePathGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'JointSpacePathGoal
    (cl:cons ':pose (pose msg))
))
