; Auto-generated. Do not edit!


(cl:in-package hdt_saffir_control-msg)


;//! \htmlinclude JointSpacePathResult.msg.html

(cl:defclass <JointSpacePathResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass JointSpacePathResult (<JointSpacePathResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JointSpacePathResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JointSpacePathResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hdt_saffir_control-msg:<JointSpacePathResult> is deprecated: use hdt_saffir_control-msg:JointSpacePathResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JointSpacePathResult>) ostream)
  "Serializes a message object of type '<JointSpacePathResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JointSpacePathResult>) istream)
  "Deserializes a message object of type '<JointSpacePathResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JointSpacePathResult>)))
  "Returns string type for a message object of type '<JointSpacePathResult>"
  "hdt_saffir_control/JointSpacePathResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JointSpacePathResult)))
  "Returns string type for a message object of type 'JointSpacePathResult"
  "hdt_saffir_control/JointSpacePathResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JointSpacePathResult>)))
  "Returns md5sum for a message object of type '<JointSpacePathResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JointSpacePathResult)))
  "Returns md5sum for a message object of type 'JointSpacePathResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JointSpacePathResult>)))
  "Returns full string definition for message of type '<JointSpacePathResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JointSpacePathResult)))
  "Returns full string definition for message of type 'JointSpacePathResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JointSpacePathResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JointSpacePathResult>))
  "Converts a ROS message object to a list"
  (cl:list 'JointSpacePathResult
))
